### ISSUE TITLE
unexpected error error_class=NameError error="uninitialized constant Fluent::TextParser"

### ISSUE THREAD

**Issue by tlytg456** [y-ken/fluent-plugin-watch-process#4]
Thank you for updating the plugin.

But when I installed run it, it also reported the following wrong:

> [root@client2 ~]# td-agent -c conf
> 2017-03-30 13:43:47 +0800 [info]: reading config file path="conf"
> 2017-03-30 13:43:47 +0800 [info]: starting fluentd-0.14.14 pid=6522
> 2017-03-30 13:43:47 +0800 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "-c", "conf", "--under-supervisor"]
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-mixin-rewrite-tag-name' version '0.1.0'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-mixin-type-converter' version '0.0.4'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-bigquery' version '0.4.2'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-bigquery' version '0.4.0'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-buffer-lightening' version '0.0.2'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-dstat' version '0.3.3'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-filter-record-map' version '0.1.4'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-graphite' version '0.0.6'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-map' version '0.2.0'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-mongo' version '0.8.1'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-mongo' version '0.8.0'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-mongo' version '0.7.16'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-proc_count' version '0.0.1'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-record-reformer' version '0.9.0'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.6'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-s3' version '0.8.2'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-s3' version '0.8.0'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-td' version '0.10.29'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-watch-process' version '0.1.0'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-webhdfs' version '1.1.0'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluentd' version '0.14.14'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluentd' version '0.14.13'
> 2017-03-30 13:43:53 +0800 [info]: gem 'fluentd' version '0.12.31'
> 2017-03-30 13:43:53 +0800 [info]: adding filter pattern="batch.process" type="record_transformer"
> 2017-03-30 13:43:53 +0800 [info]: adding match pattern="batch.*" type="stdout"
> 2017-03-30 13:43:53 +0800 [info]: adding source type="watch_process"
> 2017-03-30 13:43:53 +0800 [error]: #0 unexpected error error_class=NameError error="uninitialized constant Fluent::TextParser"
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-type-converter-0.0.4/lib/fluent/mixin/type_converter.rb:6:in `<module:TypeConverter>'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-type-converter-0.0.4/lib/fluent/mixin/type_converter.rb:3:in `<module:Mixin>'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-type-converter-0.0.4/lib/fluent/mixin/type_converter.rb:2:in `<module:Fluent>'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-type-converter-0.0.4/lib/fluent/mixin/type_converter.rb:1:in `<top (required)>'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-watch-process-0.1.0/lib/fluent/plugin/in_watch_process.rb:3:in `<top (required)>'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:121:in `require'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:121:in `require'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/registry.rb:102:in `block in search'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/registry.rb:99:in `each'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/registry.rb:99:in `search'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/registry.rb:44:in `lookup'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/plugin.rb:146:in `new_impl'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/plugin.rb:100:in `new_input'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/root_agent.rb:240:in `add_source'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/root_agent.rb:95:in `block in configure'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/root_agent.rb:92:in `each'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/root_agent.rb:92:in `configure'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/engine.rb:117:in `configure'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/engine.rb:91:in `run_configure'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/supervisor.rb:734:in `run_configure'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/supervisor.rb:503:in `block in run_worker'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/supervisor.rb:662:in `call'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/supervisor.rb:662:in `main_process'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/supervisor.rb:499:in `run_worker'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/lib/fluent/command/fluentd.rb:300:in `<top (required)>'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.14/bin/fluentd:5:in `<top (required)>'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `load'
>   2017-03-30 13:43:53 +0800 [error]: #0 /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
>   2017-03-30 13:43:53 +0800 [error]: #0 /usr/sbin/td-agent:7:in `load'
>   2017-03-30 13:43:53 +0800 [error]: #0 /usr/sbin/td-agent:7:in `<main>'

and the conf file is showed below:

> source>
> type watch_process
> tag          batch.process
> lookup_user  batchuser
> interval     10s
> /source>
> 
> filter batch.process>
>  type record_transformer
>   record>
>     hostname ${hostname}
>   /record>
> /filter>
> 
> match batch.*>
>  type stdout
> /match>

what should I do, Could you help me please?
Thank you so much.

**Comment by y-ken** [comment]
I'll fix the problem today.
Please wait a moment.

**Comment by tlytg456** [comment]
Thank you so much:）

**Comment by y-ken** [comment]
I have released that fixed the problem.
Let's try it on with following command.
```
sudo td-agent-gem install fluent-plugin-watch-process -v 0.1.1
```

**Comment by tlytg456** [comment]
It works,
Thank you~

**Comment by y-ken** [comment]
If it works well please click `star`, It get me happy
https://github.com/y-ken/fluent-plugin-watch-process
<img alt="_2017_03_30_18_57" src="https://cloud.githubusercontent.com/assets/1734549/24498837/b96322d4-157a-11e7-9d52-6a154a9d62d7.png">
